jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: pnpm run test --coverage
      - name: Codecov
        uses: codecov/codecov-action@v4.0.1

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          slug: helixdigital-io/2d-funnel-graph
          token: ${{ secrets.CODECOV_TOKEN }}

name: Test

on:
  pull_request: ~
  push:
    branches:
      - main
